### PR TITLE
Show newlines correctly

### PR DESCRIPTION
**Pull request by sihu**
Before: 
image

After:
image

### CODE REVIEW

**Comment by schmijos** [comment]
Thank you very much for addressing the issue of disappearing newlines. But actually I think the problem is how newlines land in the database probably. Can you address it there please?

**Comment by sihu** [comment]
the problem lies in the use of `innerText` which [converts newlines into](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText) `br`. The database stores the newlines as newlines as it should. By using `value` of the textarea, we can directly assign it the value with the newlines and it's displayed correctly as well.

**Comment by schmijos** [comment]
Ah, I didn't know that. Should we use `textContent` instead then?

**Review by schmijos — APPROVED** [review]
Perfection!

**Pull request merged**
